### ISSUE TITLE
installation issues - 'no module named pdcifplotter'

### ISSUE THREAD

**Issue by matsmcfly** [rowlesmr/pdCIFplotter#20]
I have followed the installation notes, and as far as I could tell everything went smoothly; however, I cant seem to run the program and I am unsure what the issue is.  I have checked that I added the \...\python310\Scripts directory to PATH

I am on windows 10, running Python 3.10 and used pip (v22.1.1) for installation.

**Comment by rowlesmr** [comment]
I'm not sure on a fix. A quick google suggest that if you add the directory in which the __init__.py file is to the PYTHONPATH environmental variable, it should work.

**Comment by matsmcfly** [comment]
thanks for your reply - I find lots of _init_.py files in different directories, but no init.py files.  I have tried adding the _init_.py files to the PYTHONPATH variable, but no joy.  I will keep trying things

**Comment by rowlesmr** [comment]
Did you install it via pip?

Can you post the output of >pip freeze  ?

**Comment by matsmcfly** [comment]
sure...
ciftostr==0.1.2
cycler==0.11.0
fonttools==4.34.4
kiwisolver==1.4.3
matplotlib==3.5.2
mplcursors==0.5.1
numpy==1.23.1
packaging==21.3
pdCIFplotter==0.1.1
Pillow==9.2.0
PyCifRW==4.4.4
pyparsing==3.0.9
PySimpleGUI==4.60.1
python-dateutil==2.8.2
six==1.16.0
traitlets==5.3.0

I am also trying to install/use ciftostr and am also experiencing problems, so I guess it is going to be something at my end

**Comment by rowlesmr** [comment]
Are you on Windows?
How are you trying to run pdcifplotter? 
At a command prompt, can you try both:
>python -m pdcifplotter
and
> pdcifplotter


Can you check if PyCifRW was installed correctly?
At a command prompt, run:
>python

and then in the python REPL, try
>>> import CifFile

it should just go to the next line and no errors appear.

**Comment by matsmcfly** [comment]
Hi, yes I am on Windows 10, 64-bit

The suggested commands give me the following errors:

C:\Users\Owner>python
Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>


C:\Users\Owner>pdcifplotter
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\pdcifplotter.exe\__main__.py", line 4, in <module>
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pdCIFplotter\__init__.py", line 3, in <module>
    from .gui import *
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pdCIFplotter\gui.py", line 11, in <module>
    from pdCIFplotter import parse_cif, plot_cif
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pdCIFplotter\parse_cif.py", line 6, in <module>
    from CifFile import CifFile, ReadCif, StarFile, CifBlock
  File "C:\Users\Owner\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\CifFile\__init__.py", line 3, in <module>
    from .StarFile import StarError,ReadStar,StarList,apply_line_folding,apply_line_prefix
ModuleNotFoundError: No module named 'CifFile.StarFile'


C:\Users\Owner>python -m pdcifplotter
C:\Users\Owner\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe: No module named pdcifplotter

**Comment by rowlesmr** [comment]
Thanks. I see two problems:

One: don't use `>python -m pdcifplotter` to start the program. I know it's in the instructions; I'll remove it a little later. (This is what your second test showed)

Two: PyCifRW isn't installed properly. (this is what your first test showed.)

You've run into a problem I identified just a little while ago re PyCifRW v4.4.4. The maintainer released a windows version that doesn't quite work - you're the first person I know of that has met the problem in the wild. Can you uninstall it, and then try one of two things: installing v4.4.3 or downloading a pre-built 4.4.3 wheel file from https://www.lfd.uci.edu/~gohlke/pythonlibs/#pycifrw that matches your python (PyCifRW‑4.4.3‑cp310‑cp310‑win_amd64.whl)

1:

- `> pip uninstall PyCifRW`
- `> pip install PyCifRW==4.4.3`
- and then follow the instructions. You'll need the compiler and things already installed on your computer as outlined in the pre-installation instructions

or

2:

- Download wheel file
- `> pip uninstall PyCifRW`
- `> pip install C:/your/folder/structure/PyCifRW‑4.4.3‑cp310‑cp310‑win_amd64.whl`

**Comment by matsmcfly** [comment]
Thanks again for the assistance, I can now confirm that the installation has worked after installing the .whl file

![image](https://user-images.githubusercontent.com/109026659/178549727-7520cb6d-2c14-450b-be86-b971698a5df8.png)

**Comment by rowlesmr** [comment]
Nice! Ciftostr should also work with the same installation of pycifrw.
